In [2]:
import numpy as np


🏋️ Задача 1: Детекція аномалій (Advanced Indexing & Masking)У тебе є масив показників тиску в системі (100, 10) (100 датчиків, 10 вимірів).Дані: data = rng.uniform(50, 150, (100, 10)).Завдання: 1. Знайди середнє значення ($\mu$) та стандартне відхилення ($\sigma$) для всієї матриці.2. Створи маску для "аномалій" — значень, які виходять за межі $[\mu - 2\sigma, \mu + 2\sigma]$.3. Заміни всі аномалії на середнє значення ($\mu$) цього ж датчика (по рядку).DE-Challenge: Зроби заміну без жодного циклу, використовуючи np.where.

In [3]:
rng = np.random.default_rng()
data = rng.uniform(50, 150, (100, 10))
mean = data.mean(axis=1, keepdims=True)
std = data.std(axis=1, keepdims=True)
mask = (data < (mean - 2*std)) | (data > (mean + 2*std))
data = np.where(mask, mean, data)
print(data)

[[100.56266053 145.18470357 125.80420054 145.66138444 123.22071937
  129.86841856  65.35060584  82.59613438  62.54423865  55.49613646]
 [ 98.17827948  52.85381446  90.23162061  98.95670218  98.77359099
  101.06854367 105.48763939  76.21489058  82.47689683  94.46117836]
 [ 76.68887083  53.33238785  63.46104256 146.15426207  78.31372782
  147.93840561 101.63850961 149.18368284  78.47729746 146.4906705 ]
 [ 76.19955407 109.56659161  77.13764207  69.08602336  83.46811289
  133.50170971 142.98812154 145.29918831  51.11903235 145.73818282]
 [147.12055222 136.28938794  99.03537493 146.16118715 137.15838049
   71.8702805  112.22850492 119.58070346 114.3297174  123.58845527]
 [ 71.13435989  64.36989624  77.75476571  53.6363653  120.23897476
   64.62536677 103.11398816 141.98390677 107.94668183  62.8557252 ]
 [ 86.32973856  55.84519266 119.76514571  52.55000616  64.70602274
  104.34796069 118.77461167  78.48803265 149.5184655   64.96183104]
 [110.8764026  142.8075765  131.01865812  84.74898525 1

### По стовпчику аксіс=0

In [25]:
features = rng.integers(1, 1000, (50, 4))
means = features.mean(axis=0, keepdims = True)
stds = features.std(axis=0, keepdims = True)
data = (features - means)/stds
new_means = data.mean(axis=0, keepdims = True)
print(new_means)


[[ 2.10942375e-17 -6.43929354e-17  4.44089210e-18 -5.10702591e-17]]


У тебе є масив статус-кодів серверів codes = [200, 404, 500, 200, 301, 502, 200].Завдання: 1. Створи маску, яка вибирає лише "критичні помилки" (всі коди $\ge 500$).2. Використовуючи цю маску, виведи не самі коди, а їхні індекси (позиції у часі).3. Використовуючи отримані індекси, дістань відповідні значення з іншого масиву timestamps (просто створи масив такої ж довжини).DE-Challenge: Використай np.argwhere або np.where, щоб отримати індекси.

In [35]:
codes = [200, 404, 500, 200, 301, 502, 200]
codes = np.array(codes)
mask = (codes >= 500)
np.argwhere(mask)
np.where(mask)[0]#Повертає плоский масив

array([2, 5])

Ковзне середнє

In [4]:
durations = rng.integers(10, 1000, 100)

In [7]:
durations.shape
window = np.ones(5)
print(np.convolve(durations, window, mode='valid')/5)

[530.2 525.  501.2 492.6 520.4 429.2 445.6 447.8 470.6 389.  335.2 294.8
 326.8 230.8 244.4 300.8 290.4 324.4 304.8 356.8 456.8 583.  694.6 683.2
 633.4 609.6 448.6 418.  470.8 571.8 600.8 627.6 662.8 726.6 671.6 660.
 609.2 562.8 519.  535.8 519.4 565.4 574.6 632.2 620.6 621.8 758.  734.8
 702.2 700.  700.  604.8 661.  575.8 678.8 575.  573.  573.4 521.2 496.2
 618.6 694.  587.4 648.4 502.6 425.6 276.8 388.  386.4 416.4 520.4 648.8
 639.  587.6 753.8 749.4 605.  537.8 693.2 513.4 511.6 535.8 611.  550.
 622.  634.  715.  595.4 511.6 469.6 320.4 324.  273.8 411.2 451.  448.4]


In [50]:
temps = rng.uniform(-10, 120, (5, 20))

In [51]:
mask = (temps > 100)|(temps <= 0)
temps[mask] = np.nan 
print(temps)
medians = np.nanmedian(temps, axis=1, keepdims=True)

temps = np.where(mask, medians, temps)
temps


[[85.7610784          nan         nan 97.69792639 93.88157789 46.79406576
  48.56280954 11.74432461  8.59499092 12.51707843         nan 87.86734937
   8.07028262  4.93677801 82.71025592         nan 77.56349461         nan
          nan         nan]
 [44.66626596 70.32774209         nan 51.29177506 87.21484181 98.19836751
          nan 63.7198739  29.2410224  66.02391526 38.44608252         nan
          nan 18.18911    87.22123391         nan  3.27520191 55.98931389
          nan 88.1380734 ]
 [54.84432057  4.99999111  3.32520259 83.54052149         nan         nan
   3.32079607         nan 46.17504457  7.57268002 23.2430636   1.66500011
  24.59107344 30.37662844         nan         nan 30.94807272 68.21724838
  57.04457898 98.87093178]
 [        nan 34.62602427 66.44788297 26.58589046 55.0486053  21.01832267
  70.87112349 36.43441423 44.48870755 43.84607084 19.1546799          nan
  15.79391494 71.73801286  9.0876026  67.29061757 61.51606521         nan
  97.15326961 34.06557048]
 [98

array([[85.7610784 , 48.56280954, 48.56280954, 97.69792639, 93.88157789,
        46.79406576, 48.56280954, 11.74432461,  8.59499092, 12.51707843,
        48.56280954, 87.86734937,  8.07028262,  4.93677801, 82.71025592,
        48.56280954, 77.56349461, 48.56280954, 48.56280954, 48.56280954],
       [44.66626596, 70.32774209, 59.85459389, 51.29177506, 87.21484181,
        98.19836751, 59.85459389, 63.7198739 , 29.2410224 , 66.02391526,
        38.44608252, 59.85459389, 59.85459389, 18.18911   , 87.22123391,
        59.85459389,  3.27520191, 55.98931389, 59.85459389, 88.1380734 ],
       [54.84432057,  4.99999111,  3.32520259, 83.54052149, 30.37662844,
        30.37662844,  3.32079607, 30.37662844, 46.17504457,  7.57268002,
        23.2430636 ,  1.66500011, 24.59107344, 30.37662844, 30.37662844,
        30.37662844, 30.94807272, 68.21724838, 57.04457898, 98.87093178],
       [43.84607084, 34.62602427, 66.44788297, 26.58589046, 55.0486053 ,
        21.01832267, 70.87112349, 36.43441423, 4

In [64]:
sales = rng.integers(1, 50, (10, 7))
cats = np.array([0, 0, 1, 2, 0, 2, 1, 0, 1, 2]) #categories
suma = np.sum(sales, axis=1, keepdims=True)#Виводить як масив вертикальний
cats = cats.reshape(10,1)
suma[cats == 0]  


array([204, 173, 187, 213])